language: rust
sudo: false
rust: nightly

matrix:
  fast_finish: true
  include:
    - name: "Linux"
      addons: 
        apt:
          packages: ["libopenmpi-dev", "openmpi-bin"]

install: cargo install cargo-mpirun
script: cargo mpirun --verbose -n 4 --example test
