language: rust
sudo: false
rust: nightly
dist: xenial

matrix:
  fast_finish: true
  include:
    - name: "Linux"
      addons: 
        apt:
          packages: ["mpich", "libmpich-dev"]

install: cargo install cargo-mpirun
script: cargo mpirun --verbose -n 4 --example test
