[package]
name = "ampi"
version = "0.1.0"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]
edition = "2018"

[dependencies]
mpi-sys = "0.1"
libc = "0.2"
futures-preview = "0.3.0-alpha.10"

[dev-dependencies]
futures-executor-preview = "0.3.0-alpha.10"