[package]
name = "hanoi"
version = "0.1.0"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]
edition = "2018"

[[bin]]
name = "hanoi"
path = "hanoi.rs"

[dependencies]
ampi = { path = "../../ampi" }
pin-utils = "0.1.0-alpha.3"
